const ALLfestivals = [
    firefly,
    leedsfestival,
    edclv,
    edco,
    electricforest,
    glastonburyfestivals,
    lostlandsfestival,
    moonrise,
    movementfestival,
    tomorrowland,
    ultramusicfestival,
    mysteryland,
    outsidelands,
    lollapalooza,
    madeinamericafest,
    readingfestival,
    wirelessfestival,
    sxsw,
    bonnaroo,
    coachella,
    loveboxfestival,
    parklife,
    austincitylimits,
    downloadfestival,
    isleofwightfestival,
    lifeisbeautiful,
    rockwerchter,
    summerfest,
    szigetfestival,
    roskilde,
    governorsballmusicfestival,
    tinthepark,
    tortugamusicfestival,
];

const CountryFestivals = [
    austincitylimits,
    lifeisbeautiful,
    rockwerchter,
    summerfest,
    tortugamusicfestival,
];

const AlternativeFestivals = [
    firefly,
    leedsfestival,
    sxsw,
    coachella,
    lifeisbeautiful,
    rockwerchter,
    summerfest,
    szigetfestival,
];

const HipHopFestivals = [
    firefly,
    leedsfestival,
    mysteryland,
    outsidelands,
    lollapalooza,
    madeinamericafest,
    readingfestival,
    wirelessfestival,
    sxsw,
    bonnaroo,
    coachella,
    loveboxfestival,
    parklife,
    austincitylimits,
    lifeisbeautiful,
    rockwerchter,
    summerfest,
    szigetfestival,
    roskilde,
    governorsballmusicfestival,
];

const RockFestivals = [
    leedsfestival,
    loveboxfestival,
    parklife,
    downloadfestival,
    isleofwightfestival,
    lifeisbeautiful,
    rockwerchter,
    summerfest,
    szigetfestival,
    roskilde,
    governorsballmusicfestival,
    tinthepark,
];

const EDMFestivals = [
    edclv,
    edco,
    electricforest,
    glastonburyfestivals,
    lostlandsfestival,
    moonrise,
    movementfestival,
    tomorrowland,
    ultramusicfestival,
    mysteryland,
    outsidelands,
    bonnaroo,
    austincitylimits,
    lifeisbeautiful,
    rockwerchter,
    summerfest,
    roskilde,
    governorsballmusicfestival,
    tinthepark,
];

const IndieFestivals = [
    coachella,
    loveboxfestival,
    austincitylimits,
    lifeisbeautiful,
    rockwerchter,
    summerfest,
    governorsballmusicfestival,
    tinthepark,
];